name: Package

on:
  push:
    branches:
      main

jobs:
  build:
    name: Build package
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Debug Visual Studio Installation
      shell: cmd
      run: |
        echo "Checking Visual Studio Installation..."
        "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease

    - name: Set up MSVC environment manually
      shell: cmd
      run: |
        @echo off
        echo Locating Visual Studio installation...
        for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -property installationPath`) do (
          echo Found Visual Studio at: %%i
          call "%%i\Common7\Tools\VsDevCmd.bat" -arch=x64
        )
        echo "Verifying MSVC setup..."
        where cl
        cl.exe /?

    - name: Build conda package
      uses: prefix-dev/rattler-build-action@v0.2.30
      with:
        # needs to be unique for each matrix entry
        recipe-path: ./recipe
        artifact-name: package-${{ matrix.target-platform }}
        build-args: --target-platform ${{ matrix.target-platform }}${{ matrix.target-platform == 'linux-aarch64' && ' --no-test' || '' }}
