name: Package

on:
  push:
    branches:
      main

jobs:
  build:
    name: Build package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   target-platform: linux-64
          - os: windows-latest
            target-platform: win-64

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSVC environment
      shell: cmd
      run: |
        @echo off
        echo Finding Visual Studio installation...
        for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
          echo Found Visual Studio at: %%i
          call "%%i\Common7\Tools\VsDevCmd.bat" -arch=x64
        )

    - name: Verify MSVC is available
      shell: cmd
      run: |
        where cl
        cl.exe /?

    - name: Build conda package
      uses: prefix-dev/rattler-build-action@v0.2.30
      with:
        # needs to be unique for each matrix entry
        recipe-path: ./recipe
        artifact-name: package-${{ matrix.target-platform }}
        build-args: --target-platform ${{ matrix.target-platform }}${{ matrix.target-platform == 'linux-aarch64' && ' --no-test' || '' }}
