name: Package

on:
  push:
    branches:
      main

jobs:
  build:
    name: Build package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   target-platform: linux-64
          # - os: ubuntu-latest
          #   target-platform: linux-aarch64
          - os: windows-latest
            target-platform: win-64
          # - os: macos-latest
          #   target-platform: osx-64
          # - os: macos-14
          #   target-platform: osx-arm64
    steps:
      - uses: actions/checkout@v4

      # Windows-specific setup for MSVC
      - name: Set up MSVC environment (Windows only)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          @echo off
          echo Locating Visual Studio installation...
          for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -property installationPath`) do (
            echo Found Visual Studio at: %%i
            call "%%i\Common7\Tools\VsDevCmd.bat" -arch=x64
          )
          echo "Verifying MSVC setup..."
          where cl
          cl.exe /?

      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.30
        with:
          # needs to be unique for each matrix entry
          recipe-path: ./recipe
          artifact-name: package-${{ matrix.target-platform }}
          build-args: --target-platform ${{ matrix.target-platform }}${{ matrix.target-platform == 'linux-aarch64' && ' --no-test' || '' }}
